name: Update M3U

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行脚本
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python update-m3u.py

      - name: 提交更新
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions@users.noreply.github.com"
          git add live.m3u
          git commit -m "Update live.m3u" || echo "No changes to commit"
          git push --force
